const courtsData = [
  {
    name: "Rizal Memorial Tennis Center",
    region: "Luzon",
    city: "Manila",
    photo: "images/rizal.jpg",
    surface: "Hard",
    indoor: false,
    lights: true,
    lat: 14.5744,
    lng: 120.9869,
    contact: "0999 888 1234",
    facebook: "https://www.facebook.com/RizalMemorialSportsComplex"
  },
  {
    name: "Toro Hills Tennis Club",
    region: "Luzon",
    city: "Quezon City",
    photo: "images/toro-hills.jpg",
    surface: "Clay",
    indoor: false,
    lights: true,
    lat: 14.6760,
    lng: 121.0437,
    contact: "0917 222 3344",
    facebook: "https://www.facebook.com/torohillstennisclub"
  },
  {
    name: "The Fort Tennis Club",
    region: "Luzon",
    city: "Taguig",
    photo: "images/fort.jpg",
    surface: "Hard",
    indoor: false,
    lights: true,
    lat: 14.5534,
    lng: 121.0450,
    contact: "0917 555 7777",
    facebook: "https://www.facebook.com/theforttennis"
  },
  {
    name: "Alabang Country Club Tennis Courts",
    region: "Luzon",
    city: "Muntinlupa",
    photo: "images/alabang.jpg",
    surface: "Clay",
    indoor: true,
    lights: true,
    lat: 14.4083,
    lng: 121.0371,
    contact: "0918 333 1111",
    facebook: "https://www.facebook.com/alabangcountryclub"
  },
  {
    name: "Philippine Columbian Tennis Club",
    region: "Luzon",
    city: "Manila",
    photo: "images/columbian.jpg",
    surface: "Hard",
    indoor: false,
    lights: false,
    lat: 14.5831,
    lng: 120.9834,
    contact: "0917 800 1122",
    facebook: "https://www.facebook.com/philippinecolumbian"
  },
  {
    name: "Valenzuela Sports Complex Tennis Court",
    region: "Luzon",
    city: "Valenzuela",
    photo: "images/valenzuela.jpg",
    surface: "Hard",
    indoor: false,
    lights: true,
    lat: 14.7009,
    lng: 120.9810,
    contact: "0932 222 0000",
    facebook: "https://www.facebook.com/valenzuelasportscomplex"
  },
  {
    name: "Subic Bay Tennis Center",
    region: "Luzon",
    city: "Subic",
    photo: "images/subic.jpg",
    surface: "Hard",
    indoor: true,
    lights: true,
    lat: 14.7994,
    lng: 120.2764,
    contact: "0920 111 2222",
    facebook: "https://www.facebook.com/subictennis"
  },
  {
    name: "Rancho Uno 1 Tennis Club",
    region: "Luzon",
    city: "Marikina",
    photo: "images/rancho-uno.jpg",
    surface: "Shell",
    indoor: false,
    lights: false,
    lat: 14.6500,
    lng: 121.1000,
    contact: "0998 456 7890",
    facebook: "https://www.facebook.com/rancho1tennis"
  },
  {
    name: "UP Diliman Tennis Courts",
    region: "Luzon",
    city: "Quezon City",
    photo: "images/up_tennis.png",
    surface: "Shell/Hard",
    indoor: false,
    lights: false,
    lat: 14.6789,
    lng: 121.0560,
    contact: "N/A",
    facebook: "https://www.facebook.com/UPDilimanTennisClub"
  },
  {
    name: "Riverside Tennis Court",
    region: "Luzon",
    city: "Pasig",
    photo: "images/riverside.jpg",
    surface: "Hard",
    indoor: false,
    lights: false,
    lat: 14.5800,
    lng: 121.0700,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "Camp Aguinaldo Tennis Court",
    region: "Luzon",
    city: "Quezon City",
    photo: "images/camp-aguinaldo.jpg",
    surface: "Shell",
    indoor: true,
    lights: true,
    lat: 14.6440,
    lng: 121.0420,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "Philippine Marines Tennis Court",
    region: "Luzon",
    city: "Taguig",
    photo: "images/philippine-marines.jpg",
    surface: "Shell",
    indoor: true,
    lights: true,
    lat: 14.5500,
    lng: 121.0500,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "Elorde Tennis Center",
    region: "Luzon",
    city: "Parañaque",
    photo: "images/elorde.jpg",
    surface: "Shell",
    indoor: false,
    lights: false,
    lat: 14.5000,
    lng: 121.0500,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "Ascott Makati Tennis Court",
    region: "Luzon",
    city: "Makati",
    photo: "images/ascott-makati.jpg",
    surface: "Synthetic Grass",
    indoor: false,
    lights: true,
    lat: 14.5580,
    lng: 121.0240,
    contact: "N/A",
    facebook: "https://www.facebook.com/AscottMakati"
  },
  {
    name: "Kerry Sports Manila",
    region: "Luzon",
    city: "Taguig",
    photo: "images/kerry-sports.jpg",
    surface: "Hard",
    indoor: false,
    lights: true,
    lat: 14.5500,
    lng: 121.0500,
    contact: "N/A",
    facebook: "https://www.facebook.com/KerrySportsManila"
  },
  {
    name: "MWSS Tennis Court",
    region: "Luzon",
    city: "Quezon City",
    photo: "images/mwss.jpg",
    surface: "Hard",
    indoor: false,
    lights: false,
    lat: 14.6500,
    lng: 121.0500,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "CCP Tennis Courts",
    region: "Luzon",
    city: "Pasay City",
    photo: "images/ccp.jpg",
    surface: "Hard",
    indoor: false,
    lights: false,
    lat: 14.5350,
    lng: 120.9810,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "Cebu Tennis Club",
    region: "Visayas",
    city: "Cebu City",
    photo: "images/cebu.jpg",
    surface: "Clay",
    indoor: false,
    lights: true,
    lat: 10.3157,
    lng: 123.8854,
    contact: "0921 888 9999",
    facebook: "https://www.facebook.com/cebutennisclub"
  },
  {
    name: "Mactan Island Tennis Club",
    region: "Visayas",
    city: "Lapu-Lapu City",
    photo: "images/mactan.jpg",
    surface: "Hard",
    indoor: false,
    lights: true,
    lat: 10.3157,
    lng: 123.9496,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "Negros Tennis Center",
    region: "Visayas",
    city: "Bacolod",
    photo: "images/negros.jpg",
    surface: "Clay",
    indoor: false,
    lights: false,
    lat: 10.6763,
    lng: 122.9568,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "Iloilo Tennis Center",
    region: "Visayas",
    city: "Iloilo City",
    photo: "images/iloilo.jpg",
    surface: "Hard",
    indoor: false,
    lights: true,
    lat: 10.7202,
    lng: 122.5621,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "Davao Tennis Complex",
    region: "Mindanao",
    city: "Davao City",
    photo: "images/davao.jpg",
    surface: "Synthetic",
    indoor: true,
    lights: false,
    lat: 7.1907,
    lng: 125.4553,
    contact: "N/A",
    facebook: "https://www.facebook.com/davaotennisclub"
  },
  {
    name: "Cagayan de Oro Tennis Center",
    region: "Mindanao",
    city: "Cagayan de Oro",
    photo: "images/cdo.jpg",
    surface: "Hard",
    indoor: false,
    lights: true,
    lat: 8.4542,
    lng: 124.6319,
    contact: "N/A",
    facebook: "https://www.facebook.com/cdotennisclub"
  },
  {
    name: "Iligan Tennis Court",
    region: "Mindanao",
    city: "Iligan City",
    photo: "images/iligan.jpg",
    surface: "Hard",
    indoor: false,
    lights: false,
    lat: 8.2280,
    lng: 124.2452,
    contact: "N/A",
    facebook: "N/A"
  },
  {
    name: "Zamboanga Tennis Court",
    region: "Mindanao",
    city: "Zamboanga City",
    photo: "images/zamboanga.jpg",
    surface: "Hard",
    indoor: false,
    lights: true,
    lat: 6.9214,
    lng: 122.0790,
    contact: "N/A",
    facebook: "N/A"
  }
];
